import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Sidebar from "@/components/sidebar";
import { BackgroundBeams } from "@/components/ui/background-beams";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#111] text-white`}>
        <div className="flex h-screen  max-w-none p-5">
          <BackgroundBeams />
          <Sidebar />
          <div className="main-content w-full ml-10  relative flex-grow overflow-y-auto custom-scrollbar">
            <main className="flex  flex-col justify-between p-6">
              {children}
            </main>
          </div>

        </div>
      </body>
    </html>
  );
}
